In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
##define the vocabulary size
voc_size = 10000

In [5]:
## one_hot representation for every word
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr


[[1837, 6869, 9651, 5335],
 [1837, 6869, 9651, 5940],
 [1837, 2712, 9651, 6693],
 [5246, 6788, 2480, 5117, 2831],
 [5246, 6788, 2480, 5117, 3827],
 [5500, 1837, 2868, 9651, 9423],
 [7851, 7757, 6372, 5117]]

In [6]:
##word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1837 6869 9651 5335]
 [   0    0    0    0 1837 6869 9651 5940]
 [   0    0    0    0 1837 2712 9651 6693]
 [   0    0    0 5246 6788 2480 5117 2831]
 [   0    0    0 5246 6788 2480 5117 3827]
 [   0    0    0 5500 1837 2868 9651 9423]
 [   0    0    0    0 7851 7757 6372 5117]]


In [9]:
## dim representation
dim = 10


In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')
model.build(input_shape=(None, sent_length))  

In [13]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step


array([[[ 0.00937865, -0.02299749,  0.02700279, -0.00153891,
         -0.04396847, -0.04969054,  0.02167794, -0.01297028,
          0.02969578, -0.04149202],
        [ 0.00937865, -0.02299749,  0.02700279, -0.00153891,
         -0.04396847, -0.04969054,  0.02167794, -0.01297028,
          0.02969578, -0.04149202],
        [ 0.00937865, -0.02299749,  0.02700279, -0.00153891,
         -0.04396847, -0.04969054,  0.02167794, -0.01297028,
          0.02969578, -0.04149202],
        [ 0.00937865, -0.02299749,  0.02700279, -0.00153891,
         -0.04396847, -0.04969054,  0.02167794, -0.01297028,
          0.02969578, -0.04149202],
        [ 0.0299728 , -0.04124142, -0.0038685 ,  0.03348884,
         -0.01168223, -0.04709858, -0.02407874,  0.00457912,
         -0.043177  , -0.04668896],
        [-0.04319487, -0.0372242 , -0.01449152,  0.00506074,
         -0.00767088,  0.03889683,  0.04516524,  0.01007328,
          0.03205648, -0.01172531],
        [-0.02834171, -0.02611356, -0.02436866,  0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 1837, 6869, 9651, 5335], dtype=int32)

In [16]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>